// Lights
export const SET_ALL_LIGHTS = "SET_ALL_LIGHTS";
export const SET_LIGHT = "SET_LIGHT";
export const EDIT_LIGHT_NAME = "EDIT_LIGHT_NAME";
export const EDIT_LIGHT_COLOR = "EDIT_LIGHT_COLOR";
export const EDIT_LED_COUNT = "EDIT_LED_COUNT";
export const SET_BRIGHTNESS = "SET_BRIGHTNESS";
export const SET_LIGHT_STATUS = "SET_LIGHT_STATUS";
// Favourite Colors
export const SET_FAVOURITE_COLORS = "SET_FAVOURITE_COLORS";
export const REMOVE_FAVOURITE_COLOR = "REMOVE_FAVOURITE_COLOR";
export const ADD_FAVOURITE_COLOR = "ADD_FAVOURITE_COLOR";
// Favourite Gradients
export const SET_FAVOURITE_GRADIENTS = "SET_FAVOURITE_GRADIENTS";
export const ADD_FAVOURITE_GRADIENT = "ADD_FAVOURITE_GRADIENT";
export const REMOVE_FAVOURITE_GRADIENT = "REMOVE_FAVOURITE_GRADIENT";
